import type { MigrationBundle } from './migrate';
// Generated by `npm run db:generate` (drizzle-kit, driver: expo). The .sql files are inlined by babel.
import migrations from '../../drizzle/migrations';

export const migrationBundle = migrations as unknown as MigrationBundle;
