// Generates src/components/logoPaths.ts from design/plus-ultra/logo-wordmark-two-tone.svg: each path's
// transform is baked into its coordinates (H/V become L), so the logo renders identically with
// react-native-svg on web and native without transform strings. Usage: node scripts/gen-logo.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const root = new URL('..', import.meta.url).pathname;
const svg = readFileSync(`${root}design/plus-ultra/logo-wordmark-two-tone.svg`, 'utf8');
const viewBox = svg.match(/viewBox="([^"]+)"/)[1];

const mul = (a, b) => [a[0] * b[0] + a[2] * b[1], a[1] * b[0] + a[3] * b[1], a[0] * b[2] + a[2] * b[3], a[1] * b[2] + a[3] * b[3], a[0] * b[4] + a[2] * b[5] + a[4], a[1] * b[4] + a[3] * b[5] + a[5]];
const rad = (d) => (d * Math.PI) / 180;
function matrix(transform) {
  let m = [1, 0, 0, 1, 0, 0];
  for (const [, fn, args] of transform.matchAll(/(\w+)\(([^)]*)\)/g)) {
    const n = args.trim().split(/[\s,]+/).map(Number);
    const t = {
      translate: () => [1, 0, 0, 1, n[0], n[1] ?? 0],
      scale: () => [n[0], 0, 0, n[1] ?? n[0], 0, 0],
      rotate: () => [Math.cos(rad(n[0])), Math.sin(rad(n[0])), -Math.sin(rad(n[0])), Math.cos(rad(n[0])), 0, 0],
      skewX: () => [1, 0, Math.tan(rad(n[0])), 1, 0, 0],
    }[fn];
    if (!t) throw new Error(`unsupported transform ${fn}`);
    m = mul(m, t());
  }
  return m;
}

function bake(d, m) {
  const out = [];
  const pt = (x, y) => [m[0] * x + m[2] * y + m[4], m[1] * x + m[3] * y + m[5]].map((v) => +v.toFixed(1)).join(' ');
  let x = 0;
  let y = 0;
  for (const [, cmd, rest] of d.matchAll(/([MLQHVZ])([^MLQHVZ]*)/g)) {
    const n = rest.trim() ? rest.trim().split(/[\s,]+/).map(Number) : [];
    if (cmd === 'M' || cmd === 'L') for (let i = 0; i < n.length; i += 2) { [x, y] = [n[i], n[i + 1]]; out.push(`${i === 0 ? cmd : 'L'}${pt(x, y)}`); }
    else if (cmd === 'Q') for (let i = 0; i < n.length; i += 4) { out.push(`Q${pt(n[i], n[i + 1])} ${pt(n[i + 2], n[i + 3])}`); [x, y] = [n[i + 2], n[i + 3]]; }
    else if (cmd === 'H') for (const v of n) { x = v; out.push(`L${pt(x, y)}`); }
    else if (cmd === 'V') for (const v of n) { y = v; out.push(`L${pt(x, y)}`); }
    else out.push('Z');
  }
  return out.join('');
}

const paths = [...svg.matchAll(/<path d="([^"]+)" transform="([^"]+)" fill="([^"]+)"\/>/g)].map(([, d, t, fill]) => ({ part: fill === '#39FF14' ? 'ltra' : 'plus', d: bake(d, matrix(t)) }));
const src = `// Generated by scripts/gen-logo.mjs from design/plus-ultra/logo-wordmark-two-tone.svg. Do not edit.
export const LOGO_VIEWBOX = '${viewBox}';
export const LOGO_PATHS: { part: 'plus' | 'ltra'; d: string }[] = ${JSON.stringify(paths, null, 2)};
`;
writeFileSync(`${root}src/components/logoPaths.ts`, src);
console.log(`${paths.length} paths`);
